### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by cliobeach** [sandijean90/covid-19#1]
good job, it's easy to understand by using the fastai, and my question is how can I use the result of fastai to predict an image that is not in the dataset, eg. a image from the internet.

**Comment by sandijean90** [comment]
Hi @cliobeach ! This depends on what version of FastAi you have. This article is a great reference for predicting on a new single image. It has examples for both V1 and V0.
([https://forums.fast.ai/t/fastai-v1-predicting-on-single-new-image-conversion-to-fastai-image-from-png-image/30427])
